# Generated by Django 5.2.7 on 2025-10-13 02:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('telefono_cliente', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('fecha_cita', models.DateTimeField(verbose_name='Fecha y Hora de la Cita')),
                ('tipo_cita', models.CharField(choices=[('normal', 'Cita Normal'), ('prioritaria', 'Cita Prioritaria')], default='normal', max_length=20, verbose_name='Tipo de Cita')),
                ('ingresos_mensuales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ingresos Mensuales')),
                ('tipo_credito', models.CharField(blank=True, choices=[('infonavit', 'Infonavit'), ('fovissste', 'Fovissste'), ('bancario', 'Crédito Bancario'), ('contado', 'Contado')], max_length=20, null=True, verbose_name='Tipo de Crédito')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('google_event_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID del Evento en Google Calendar')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_cita'],
            },
        ),
    ]
