# Generated by Django 5.2.7 on 2025-11-20 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_disponible', models.DateField(help_text='Día en el que se pueden agendar citas', verbose_name='Fecha Disponible')),
                ('tipo_cita', models.CharField(choices=[('normal', 'Cita Normal'), ('prioritaria', 'Cita Prioritaria')], max_length=20, verbose_name='Tipo de Cita')),
                ('capacidad_maxima', models.PositiveIntegerField(default=3, help_text='Número máximo de citas permitidas en este día', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad Máxima')),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas sobre la disponibilidad de este día', verbose_name='Notas del Administrador')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Día Disponible',
                'verbose_name_plural': 'Días Disponibles',
                'ordering': ['fecha_disponible', 'tipo_cita'],
                'indexes': [models.Index(fields=['fecha_disponible', 'tipo_cita'], name='appointment_fecha_d_47f778_idx')],
                'unique_together': {('fecha_disponible', 'tipo_cita')},
            },
        ),
    ]
