# Generated by Django 5.2.7 on 2025-10-13 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='Token de Acceso')),
                ('refresh_token', models.TextField(verbose_name='Token de Actualización')),
                ('token_uri', models.CharField(max_length=300, verbose_name='URI del Token')),
                ('client_id', models.CharField(max_length=300, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=300, verbose_name='Client Secret')),
                ('scopes', models.TextField(verbose_name='Scopes (permisos)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Administrador')),
            ],
            options={
                'verbose_name': 'Token de Google API',
                'verbose_name_plural': 'Tokens de Google API',
            },
        ),
    ]
